//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_6_MaxVasushko_ISP_411.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ProductId { get; set; }
        public string ProductArticle { get; set; }
        public int ProductNameId { get; set; }
        public int ProductUnitId { get; set; }
        public decimal ProductPrice { get; set; }
        public Nullable<int> ProductMaxDiscount { get; set; }
        public int ProductManufacturerId { get; set; }
        public int ProductSupplierId { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductDiscountNow { get; set; }
        public int ProductStock { get; set; }
        public string ProductDescription { get; set; }
        public byte[] ProductPhotoImage { get; set; }
        public string ProductPhotoName { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Names Names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Units Units { get; set; }
    }
}
